name: Weekly deploy

on:
  schedule:
    # every sunday
    - cron: '0 0 * * 0'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: install
        run: npm install
      - name: analyze
        run: npm run analyze
      - name: build
        run: npm run build
      - name: deploy
        run: npx exoframe -u -e https://exoframe.codezen.net -t $EXO_TOKEN
        env:
          EXO_TOKEN: ${{ secrets.EXO_TOKEN }}
